name: auto merge dev to master

on:
  schedule:
    - cron:  '30 5,13 * * *'
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-18-04
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          labels: auto_merge, deploy-ready
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ format('Update json data {0}', github.event.head_commit.timestamp) }}
          base: development
          branch: master